project:
  type: book
  output-dir: docs

book:
  title: "Template"
  author: "TWU Online"
  date: "last-modified"
  date-format: "MMM D, YYYY"
  chapters:
    - index.qmd
    - u1.qmd
    - u2.qmd
    - u3.qmd
    - u4.qmd
    - u5.qmd
    - u6.qmd

# Note: If you do not have any Zotero references (and a "Better BibLatex" references.bib file) in your course, you should comment-out (add "#" to the beginning of each line) the References section below or else you will get the "compilation failed- error" message when you render the Quarto project.
# ------------Start of References Section----------------
    - references.qmd

bibliography: references.bib
csl: apa.csl
link-bibliography: true
link-citations: true
# ------------End of References Section----------------

format:
  html:
    toc-depth: 4
    theme: cosmo
    include-in-header:
      - text: |
          <script src="https://twuonline.github.io/course-materials/twu_global_header.js"></script>
  pdf:
    documentclass: scrreprt
  docx:
    toc: true
    number-sections: true
    highlight-style: github

fig-cap-location: top
lightbox:
  desc-position: top

