# version 1.2

project:
  type: book
  output-dir: docs

# Changing metadata labels: https://quarto.org/docs/authoring/title-blocks.html#metadata-labels
published-title: "Last Modified"

book:
  title: "Template"
  author: "TWU Online"
  date: "last-modified"
  date-format: "MMM D, YYYY"
  chapters:
    - index.qmd
    - u1.qmd
    - u2.qmd
    - u3.qmd
    - u4.qmd
    - u5.qmd
    - u6.qmd
    - references.qmd

# References
bibliography: https://twuonline.github.io/course-materials/quarto/references.bib
csl: https://twuonline.github.io/course-materials/quarto/apa.csl
link-bibliography: true
link-citations: true

# Formats
format:
# Format - HTML
  html:
    css: https://twuonline.github.io/course-materials/quarto/twu_styles.css
    toc-depth: 4
    theme: cosmo
    include-in-header:
      - text: |
          <script src="https://twuonline.github.io/course-materials/quarto/twu_global_header.js"></script>
          <link rel = "shortcut icon" href = "https://twuonline.github.io/course-materials/quarto/favicon.ico" />
# Format - PDF
  pdf:
    documentclass: scrreprt
# Format - Doc
  docx:
    toc: true
    number-sections: true
    highlight-style: github

# Fig captions
fig-cap-location: top
lightbox:
  desc-position: top

